
!                          -------------------
!                          W  A  R  N  I  N  G
!                          -------------------
!
!   This code fragment is automatically generated by MAPL_GridCompSpecs_ACG.
!   Please DO NOT edit it. Any modification made in here will be overwritten
!   next time this file is auto-generated. Instead, enter your additions
!   or deletions in the .rc file in the src tree.
!
    
   call MAPL_GetPointer(import, FROCEAN, 'FROCEAN', rc=status); VERIFY_(status)
   
   call MAPL_GetPointer(import, TAUX, 'TAUX', rc=status); VERIFY_(status)
   
   call MAPL_GetPointer(import, TAUY, 'TAUY', rc=status); VERIFY_(status)
   
   call MAPL_GetPointer(import, PENUVR, 'PENUVR', rc=status); VERIFY_(status)
   
   call MAPL_GetPointer(import, PENPAR, 'PENPAR', rc=status); VERIFY_(status)
   
   call MAPL_GetPointer(import, PENUVF, 'PENUVF', rc=status); VERIFY_(status)
   
   call MAPL_GetPointer(import, PENPAF, 'PENPAF', rc=status); VERIFY_(status)
   
   call MAPL_GetPointer(import, DRNIR, 'DRNIR', rc=status); VERIFY_(status)
   
   call MAPL_GetPointer(import, DFNIR, 'DFNIR', rc=status); VERIFY_(status)
   
   call MAPL_GetPointer(import, SWHEAT, 'SWHEAT', rc=status); VERIFY_(status)
   
   call MAPL_GetPointer(import, DISCHARGE, 'DISCHARGE', rc=status); VERIFY_(status)
   
   if (trim(OCEAN_NAME) == 'MOM') then
      call MAPL_GetPointer(import, TR, 'TR', rc=status); VERIFY_(status)
   else
      nullify(TR)
   endif
   
   if (trim(OCEAN_NAME) == 'MOM') then
      call MAPL_GetPointer(import, TRFLUX, 'TRFLUX', rc=status); VERIFY_(status)
   else
      nullify(TRFLUX)
   endif
   
   call MAPL_GetPointer(import, LWFLX, 'LWFLX', rc=status); VERIFY_(status)
   
   call MAPL_GetPointer(import, SHFLX, 'SHFLX', rc=status); VERIFY_(status)
   
   call MAPL_GetPointer(import, QFLUX, 'QFLUX', rc=status); VERIFY_(status)
   
   call MAPL_GetPointer(import, SNOW, 'SNOW', rc=status); VERIFY_(status)
   
   call MAPL_GetPointer(import, RAIN, 'RAIN', rc=status); VERIFY_(status)
   
   call MAPL_GetPointer(import, FRESH, 'FRESH', rc=status); VERIFY_(status)
   
   call MAPL_GetPointer(import, FSALT, 'FSALT', rc=status); VERIFY_(status)
   
   call MAPL_GetPointer(import, FHOCN, 'FHOCN', rc=status); VERIFY_(status)
   
   call MAPL_GetPointer(import, PEN_OCN, 'PEN_OCN', rc=status); VERIFY_(status)
   
   if (dual_ocean) then
      call MAPL_GetPointer(import, FRACICEd, 'FRACICEd', rc=status); VERIFY_(status)
   else
      nullify(FRACICEd)
   endif
   
   call MAPL_GetPointer(export, MASKO, 'MASKO', rc=status); VERIFY_(status)
   
   call MAPL_GetPointer(export, SS_FOUND, 'SS_FOUND', rc=status); VERIFY_(status)
   
   call MAPL_GetPointer(export, FRZMLT, 'FRZMLT', rc=status); VERIFY_(status)
   
   call MAPL_GetPointer(export, TAUX, 'TAUX', rc=status); VERIFY_(status)
   
   call MAPL_GetPointer(export, TAUY, 'TAUY', rc=status); VERIFY_(status)
   
   call MAPL_GetPointer(export, SWHEAT, 'SWHEAT', rc=status); VERIFY_(status)
   
   call MAPL_GetPointer(export, RFLUX, 'RFLUX', rc=status); VERIFY_(status)
   
   call MAPL_GetPointer(export, DISCHARGE, 'DISCHARGE', rc=status); VERIFY_(status)
   
   call MAPL_GetPointer(export, FROCEAN, 'FROCEAN', rc=status); VERIFY_(status)
   
   call MAPL_GetPointer(export, LWFLX, 'LWFLX', rc=status); VERIFY_(status)
   
   call MAPL_GetPointer(export, SWFLX, 'SWFLX', rc=status); VERIFY_(status)
   
   call MAPL_GetPointer(export, SHFLX, 'SHFLX', rc=status); VERIFY_(status)
   
   call MAPL_GetPointer(export, QFLUX, 'QFLUX', rc=status); VERIFY_(status)
   
   call MAPL_GetPointer(export, SFLX, 'SFLX', rc=status); VERIFY_(status)
   
   call MAPL_GetPointer(export, RAIN, 'RAIN', rc=status); VERIFY_(status)
   
   call MAPL_GetPointer(export, SNOW, 'SNOW', rc=status); VERIFY_(status)
   
   call MAPL_GetPointer(export, PEN_OCN, 'PEN_OCN', rc=status); VERIFY_(status)
   
   call MAPL_GetPointer(internal, TS_FOUND, 'TS_FOUND', rc=status); VERIFY_(status)
   