
!                          -------------------
!                          W  A  R  N  I  N  G
!                          -------------------
!
!   This code fragment is automatically generated by MAPL_GridCompSpecs_ACG.
!   Please DO NOT edit it. Any modification made in here will be overwritten
!   next time this file is auto-generated. Instead, enter your additions
!   or deletions in the .rc file in the src tree.
!
    
   call MAPL_AddExportSpec(gc,&
        & short_name='MASKO', &
        & units='1', &
        & dims=MAPL_DimsHorzOnly, &
        & vlocation=MAPL_VlocationNone, &
        & rc=status)
        VERIFY_(status)
   
   call MAPL_AddExportSpec(gc,&
        & short_name='SS_FOUND', &
        & units='PSU', &
        & dims=MAPL_DimsHorzOnly, &
        & vlocation=MAPL_VlocationNone, &
        & rc=status)
        VERIFY_(status)
   
   call MAPL_AddExportSpec(gc,&
        & short_name='FRZMLT', &
        & units='W m-2', &
        & dims=MAPL_DimsHorzOnly, &
        & vlocation=MAPL_VlocationNone, &
        & rc=status)
        VERIFY_(status)
   
   call MAPL_AddExportSpec(gc,&
        & short_name='TAUX', &
        & units='N m-2', &
        & dims=MAPL_DimsHorzOnly, &
        & vlocation=MAPL_VlocationNone, &
        & rc=status)
        VERIFY_(status)
   
   call MAPL_AddExportSpec(gc,&
        & short_name='TAUY', &
        & units='N m-2', &
        & dims=MAPL_DimsHorzOnly, &
        & vlocation=MAPL_VlocationNone, &
        & rc=status)
        VERIFY_(status)
   
   call MAPL_AddExportSpec(gc,&
        & short_name='SWHEAT', &
        & units='W m-2', &
        & dims=MAPL_DimsHorzVert, &
        & vlocation=MAPL_VlocationCenter, &
        & rc=status)
        VERIFY_(status)
   
   call MAPL_AddExportSpec(gc,&
        & short_name='RFLUX', &
        & units='W m-2', &
        & dims=MAPL_DimsHorzOnly, &
        & vlocation=MAPL_VlocationNone, &
        & rc=status)
        VERIFY_(status)
   
   call MAPL_AddExportSpec(gc,&
        & short_name='DISCHARGE', &
        & units='kg m-2 s-1', &
        & dims=MAPL_DimsHorzOnly, &
        & vlocation=MAPL_VlocationNone, &
        & rc=status)
        VERIFY_(status)
   
   call MAPL_AddExportSpec(gc,&
        & short_name='FROCEAN', &
        & units='1', &
        & dims=MAPL_DimsHorzOnly, &
        & vlocation=MAPL_VlocationNone, &
        & rc=status)
        VERIFY_(status)
   
   call MAPL_AddExportSpec(gc,&
        & short_name='LWFLX', &
        & units='W m-2', &
        & dims=MAPL_DimsHorzOnly, &
        & vlocation=MAPL_VlocationNone, &
        & rc=status)
        VERIFY_(status)
   
   call MAPL_AddExportSpec(gc,&
        & short_name='SWFLX', &
        & units='W m-2', &
        & dims=MAPL_DimsHorzOnly, &
        & vlocation=MAPL_VlocationNone, &
        & rc=status)
        VERIFY_(status)
   
   call MAPL_AddExportSpec(gc,&
        & short_name='SHFLX', &
        & units='W m-2', &
        & dims=MAPL_DimsHorzOnly, &
        & vlocation=MAPL_VlocationNone, &
        & rc=status)
        VERIFY_(status)
   
   call MAPL_AddExportSpec(gc,&
        & short_name='QFLUX', &
        & units='kg m-2 s-1', &
        & dims=MAPL_DimsHorzOnly, &
        & vlocation=MAPL_VlocationNone, &
        & rc=status)
        VERIFY_(status)
   
   call MAPL_AddExportSpec(gc,&
        & short_name='SFLX', &
        & units='kg m-2 s-1', &
        & dims=MAPL_DimsHorzOnly, &
        & vlocation=MAPL_VlocationNone, &
        & rc=status)
        VERIFY_(status)
   
   call MAPL_AddExportSpec(gc,&
        & short_name='RAIN', &
        & units='kg m-2 s-1', &
        & dims=MAPL_DimsHorzOnly, &
        & vlocation=MAPL_VlocationNone, &
        & rc=status)
        VERIFY_(status)
   
   call MAPL_AddExportSpec(gc,&
        & short_name='SNOW', &
        & units='kg m-2 s-1', &
        & dims=MAPL_DimsHorzOnly, &
        & vlocation=MAPL_VlocationNone, &
        & rc=status)
        VERIFY_(status)
   
   call MAPL_AddExportSpec(gc,&
        & short_name='PEN_OCN', &
        & units='W m-2', &
        & dims=MAPL_DimsHorzOnly, &
        & vlocation=MAPL_VlocationNone, &
        & rc=status)
        VERIFY_(status)
   