
!                          -------------------
!                          W  A  R  N  I  N  G
!                          -------------------
!
!   This code fragment is automatically generated by MAPL_GridCompSpecs_ACG.
!   Please DO NOT edit it. Any modification made in here will be overwritten
!   next time this file is auto-generated. Instead, enter your additions
!   or deletions in the .rc file in the src tree.
!
    
   call MAPL_AddInternalSpec(gc,&
        & short_name='TS_FOUND', &
        & units='K', &
        & dims=MAPL_DimsHorzOnly, &
        & vlocation=MAPL_VlocationNone, &
        & default=280.0, &
        & friendlyto='trim(COMP_NAME)', &
        & rc=status)
        VERIFY_(status)
   