
!                          -------------------
!                          W  A  R  N  I  N  G
!                          -------------------
!
!   This code fragment is automatically generated by MAPL_GridCompSpecs_ACG.
!   Please DO NOT edit it. Any modification made in here will be overwritten
!   next time this file is auto-generated. Instead, enter your additions
!   or deletions in the .rc file in the src tree.
!
    
   real, pointer, dimension(:,:) :: FROCEAN => null()
   real, pointer, dimension(:,:) :: TAUX => null()
   real, pointer, dimension(:,:) :: TAUY => null()
   real, pointer, dimension(:,:) :: PENUVR => null()
   real, pointer, dimension(:,:) :: PENPAR => null()
   real, pointer, dimension(:,:) :: PENUVF => null()
   real, pointer, dimension(:,:) :: PENPAF => null()
   real, pointer, dimension(:,:) :: DRNIR => null()
   real, pointer, dimension(:,:) :: DFNIR => null()
   real, pointer, dimension(:,:,:) :: SWHEAT => null()
   real, pointer, dimension(:,:) :: DISCHARGE => null()
   real, pointer, dimension(:,:,:) :: TR => null()
   real, pointer, dimension(:,:) :: TRFLUX => null()
   real, pointer, dimension(:,:) :: LWFLX => null()
   real, pointer, dimension(:,:) :: SHFLX => null()
   real, pointer, dimension(:,:) :: QFLUX => null()
   real, pointer, dimension(:,:) :: SNOW => null()
   real, pointer, dimension(:,:) :: RAIN => null()
   real, pointer, dimension(:,:) :: FRESH => null()
   real, pointer, dimension(:,:) :: FSALT => null()
   real, pointer, dimension(:,:) :: FHOCN => null()
   real, pointer, dimension(:,:) :: PEN_OCN => null()
   real, pointer, dimension(:,:) :: FRACICEd => null()
   real, pointer, dimension(:,:) :: MASKO => null()
   real, pointer, dimension(:,:) :: SS_FOUND => null()
   real, pointer, dimension(:,:) :: FRZMLT => null()
   real, pointer, dimension(:,:) :: TAUX => null()
   real, pointer, dimension(:,:) :: TAUY => null()
   real, pointer, dimension(:,:,:) :: SWHEAT => null()
   real, pointer, dimension(:,:) :: RFLUX => null()
   real, pointer, dimension(:,:) :: DISCHARGE => null()
   real, pointer, dimension(:,:) :: FROCEAN => null()
   real, pointer, dimension(:,:) :: LWFLX => null()
   real, pointer, dimension(:,:) :: SWFLX => null()
   real, pointer, dimension(:,:) :: SHFLX => null()
   real, pointer, dimension(:,:) :: QFLUX => null()
   real, pointer, dimension(:,:) :: SFLX => null()
   real, pointer, dimension(:,:) :: RAIN => null()
   real, pointer, dimension(:,:) :: SNOW => null()
   real, pointer, dimension(:,:) :: PEN_OCN => null()
   real, pointer, dimension(:,:) :: TS_FOUND => null()