
!                          -------------------
!                          W  A  R  N  I  N  G
!                          -------------------
!
!   This code fragment is automatically generated by MAPL_GridCompSpecs_ACG.
!   Please DO NOT edit it. Any modification made in here will be overwritten
!   next time this file is auto-generated. Instead, enter your additions
!   or deletions in the .rc file in the src tree.
!
    
   call MAPL_AddImportSpec(gc,&
        & short_name='FROCEAN', &
        & units='1', &
        & dims=MAPL_DimsHorzOnly, &
        & vlocation=MAPL_VlocationNone, &
        & rc=status)
        VERIFY_(status)
   
   call MAPL_AddImportSpec(gc,&
        & short_name='TAUX', &
        & units='N m-2', &
        & dims=MAPL_DimsHorzOnly, &
        & vlocation=MAPL_VlocationNone, &
        & rc=status)
        VERIFY_(status)
   
   call MAPL_AddImportSpec(gc,&
        & short_name='TAUY', &
        & units='N m-2', &
        & dims=MAPL_DimsHorzOnly, &
        & vlocation=MAPL_VlocationNone, &
        & rc=status)
        VERIFY_(status)
   
   call MAPL_AddImportSpec(gc,&
        & short_name='PENUVR', &
        & units='W m-2', &
        & dims=MAPL_DimsHorzOnly, &
        & vlocation=MAPL_VlocationNone, &
        & rc=status)
        VERIFY_(status)
   
   call MAPL_AddImportSpec(gc,&
        & short_name='PENPAR', &
        & units='W m-2', &
        & dims=MAPL_DimsHorzOnly, &
        & vlocation=MAPL_VlocationNone, &
        & rc=status)
        VERIFY_(status)
   
   call MAPL_AddImportSpec(gc,&
        & short_name='PENUVF', &
        & units='W m-2', &
        & dims=MAPL_DimsHorzOnly, &
        & vlocation=MAPL_VlocationNone, &
        & rc=status)
        VERIFY_(status)
   
   call MAPL_AddImportSpec(gc,&
        & short_name='PENPAF', &
        & units='W m-2', &
        & dims=MAPL_DimsHorzOnly, &
        & vlocation=MAPL_VlocationNone, &
        & rc=status)
        VERIFY_(status)
   
   call MAPL_AddImportSpec(gc,&
        & short_name='DRNIR', &
        & units='W m-2', &
        & dims=MAPL_DimsHorzOnly, &
        & vlocation=MAPL_VlocationNone, &
        & rc=status)
        VERIFY_(status)
   
   call MAPL_AddImportSpec(gc,&
        & short_name='DFNIR', &
        & units='W m-2', &
        & dims=MAPL_DimsHorzOnly, &
        & vlocation=MAPL_VlocationNone, &
        & rc=status)
        VERIFY_(status)
   
   call MAPL_AddImportSpec(gc,&
        & short_name='SWHEAT', &
        & units='W m-2', &
        & dims=MAPL_DimsHorzVert, &
        & vlocation=MAPL_VlocationCenter, &
        & rc=status)
        VERIFY_(status)
   
   call MAPL_AddImportSpec(gc,&
        & short_name='DISCHARGE', &
        & units='kg m-2 s-1', &
        & dims=MAPL_DimsHorzOnly, &
        & vlocation=MAPL_VlocationNone, &
        & rc=status)
        VERIFY_(status)
   
   if (trim(OCEAN_NAME) == 'MOM') then
      call MAPL_AddImportSpec(gc,&
           & short_name='TR', &
           & units='1', &
           & dims=MAPL_DimsHorzVert, &
           & vlocation=MAPL_VlocationCenter, &
           & rc=status)
           VERIFY_(status)
   endif
   
   if (trim(OCEAN_NAME) == 'MOM') then
      call MAPL_AddImportSpec(gc,&
           & short_name='TRFLUX', &
           & units='X', &
           & dims=MAPL_DimsHorzOnly, &
           & vlocation=MAPL_VlocationNone, &
           & rc=status)
           VERIFY_(status)
   endif
   
   call MAPL_AddImportSpec(gc,&
        & short_name='LWFLX', &
        & units='W m-2', &
        & dims=MAPL_DimsHorzOnly, &
        & vlocation=MAPL_VlocationNone, &
        & rc=status)
        VERIFY_(status)
   
   call MAPL_AddImportSpec(gc,&
        & short_name='SHFLX', &
        & units='W m-2', &
        & dims=MAPL_DimsHorzOnly, &
        & vlocation=MAPL_VlocationNone, &
        & rc=status)
        VERIFY_(status)
   
   call MAPL_AddImportSpec(gc,&
        & short_name='QFLUX', &
        & units='kg m-2 s-1', &
        & dims=MAPL_DimsHorzOnly, &
        & vlocation=MAPL_VlocationNone, &
        & rc=status)
        VERIFY_(status)
   
   call MAPL_AddImportSpec(gc,&
        & short_name='SNOW', &
        & units='kg m-2 s-1', &
        & dims=MAPL_DimsHorzOnly, &
        & vlocation=MAPL_VlocationNone, &
        & rc=status)
        VERIFY_(status)
   
   call MAPL_AddImportSpec(gc,&
        & short_name='RAIN', &
        & units='kg m-2 s-1', &
        & dims=MAPL_DimsHorzOnly, &
        & vlocation=MAPL_VlocationNone, &
        & rc=status)
        VERIFY_(status)
   
   call MAPL_AddImportSpec(gc,&
        & short_name='FRESH', &
        & units='kg m-2 s-1', &
        & dims=MAPL_DimsHorzOnly, &
        & vlocation=MAPL_VlocationNone, &
        & rc=status)
        VERIFY_(status)
   
   call MAPL_AddImportSpec(gc,&
        & short_name='FSALT', &
        & units='kg m-2 s-1', &
        & dims=MAPL_DimsHorzOnly, &
        & vlocation=MAPL_VlocationNone, &
        & rc=status)
        VERIFY_(status)
   
   call MAPL_AddImportSpec(gc,&
        & short_name='FHOCN', &
        & units='W m-2', &
        & dims=MAPL_DimsHorzOnly, &
        & vlocation=MAPL_VlocationNone, &
        & rc=status)
        VERIFY_(status)
   
   call MAPL_AddImportSpec(gc,&
        & short_name='PEN_OCN', &
        & units='W m-2', &
        & dims=MAPL_DimsHorzOnly, &
        & vlocation=MAPL_VlocationNone, &
        & rc=status)
        VERIFY_(status)
   
   if (dual_ocean) then
      call MAPL_AddImportSpec(gc,&
           & short_name='FRACICEd', &
           & units='1', &
           & dims=MAPL_DimsHorzOnly, &
           & vlocation=MAPL_VlocationNone, &
           & rc=status)
           VERIFY_(status)
   endif
   